service: lexico
custom: ${file(infra/environments/${opt:stage}.yml)}

provider:
  name: aws
  region: us-east-1
  stage: ${self:custom.stage}
  runtime: nodejs12.x
  memorySize: 128
  timeout: 16
  role: Role
  deploymentBucket:
    name: lexico-deploy
    serverSideEncryption: AES256
  versionFunctions: false
  environment:
    ENV: ${self:custom.stage}
  httpApi:
    name: lexico-${self:provider.stage}
    payload: '2.0'
    cors: true

package:
  individually: true

functions: ${self:custom.lambda}

resources:
  Resources:
    Role: ${self:custom.iam.Role}
    DictionaryBucket: ${self:custom.s3.DictionaryBucket}
    LiteratureBucket: ${self:custom.s3.LiteratureBucket}
    StaticSiteBucket: ${self:custom.s3.StaticSiteBucket}
    PublicReadGetObjectPolicy: ${self:custom.s3.PublicReadGetObjectPolicy}
