Search:
  name: lexico-search-${self:provider.stage}
  handler: search.search
  package:
    artifact: search.zip
  events:
    - httpApi: GET /search

Literature:
  name: lexico-literature-${self:provider.stage}
  handler: literature.literature
  package:
    artifact: literature.zip
  events:
    - httpApi: GET /literature